version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
  eureka-server:
    image: queuew/eureka:latest
    container_name: eureka
    environment:
      - EUREKA_HOST=eureka-server
    ports:
      - "8761:8080"
  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=user-service
      - POSTGRES_PASSWORD=user-service
    ports:
      - "5432:5432"

  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: .
    depends_on:
      - kafka
      - db
      - eureka-server
    environment:
      - DB_URL=jdbc:postgresql://db:5432/user-service
      - DB_LOGIN=user-service
      - DB_PASSWORD=user-service
      - KAFKA_BROKERS=http://kafka:9092
      - TRACING_BASEURL=http://10.10.15.124:9411
      - EUREKA_URL=http://eureka-server:8080/eureka
      - AFINNY_EMAIL=afinny.test@gmail.com
      - AFINNY_EMAIL_PASSWORD=!2345Qwert
    ports:
      - "8081:8080"
  rc-redis:
    container_name: rc-redis
    image: redis:5
    ports:
      - "6379:6379"
    restart: always
