spring:
  application:
    name: ${APPLICATION_NAME:api-gateway}

  # Data Source properties
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.17.1.4:5432/afinny?currentSchema=${spring.application.name}}
    platform: postgres
    username": ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${DATASOURCE_POOL_MAX_SIZE:10}
      minimum-idle: ${DATASOURCE_POOL_MIN_IDLE:1}


  # SQL queries
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Maximum allowed file size
  servlet:
    multipart:
      max-file-size: 16MB

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:172.17.1.4:9092}

  zipkin:
    baseUrl: ${TRACING_BASEURL:http://localhost:9411/}
    sender:
      type: ${TRACING_SENDER_TYPE:kafka}
    kafka:
      topic: ${TRACING_KAFKA_TOPIC:tracing_topic}
    service:
      name: ${TRACING_SERVICE_NAME:dev-api-gateway}
  sleuth:
    sampler:
      probability: 1
  # Redis
  cache:
    type: redis
  redis:
    host: ${REDIS_DB:172.17.1.4}
    port: 6379

# Actuator
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761/eureka}
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
feign:
  httpclient:
    enabled: true

  # Https
server:
  ssl:
    key-store: file:afinny.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: afinny
    key-password: password
    enabled: true